# Generated by Django 2.1.7 on 2019-03-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_type', models.CharField(choices=[('TENANT', 'TENANT'), ('OWNER', 'OWNER'), ('ADMIN', 'ADMIN'), ('TEST', 'TEST')], default='TEST', max_length=64)),
                ('account_status', models.CharField(choices=[('NEW', 'NEW'), ('VERIFIED', 'VERIFIED'), ('SUSPENDED', 'SUSPENDED')], default='NEW', max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('contact_number', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='email address')),
                ('account_id', models.CharField(default='FFFF', max_length=256, unique=True)),
                ('password', models.CharField(default='FFFF', max_length=256)),
                ('secret_key', models.CharField(blank=True, max_length=64)),
                ('password_reset_token', models.CharField(blank=True, max_length=512)),
                ('bank_bsb', models.CharField(blank=True, max_length=64)),
                ('bank_no', models.CharField(blank=True, max_length=128)),
                ('bank_name', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('DISPUTE', 'DISPUTE'), ('COMPLETE', 'COMPLETE')], default='NEW', max_length=64)),
                ('is_confirmed_by_tenant', models.CharField(default='NO', max_length=64)),
                ('is_confirmed_by_owner', models.CharField(default='NO', max_length=64)),
                ('ejari_no', models.CharField(max_length=128)),
                ('premis_no', models.CharField(max_length=128)),
                ('internal_id', models.CharField(max_length=128)),
                ('tenant_id', models.CharField(max_length=512)),
                ('owner_id', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=256)),
                ('total_contract_value', models.CharField(blank=True, max_length=128)),
                ('property_usage', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], default='RESIDENTIAL', max_length=64)),
                ('annual_rent', models.CharField(blank=True, max_length=64)),
                ('property_size', models.CharField(blank=True, max_length=64)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('deposit_holding', models.CharField(blank=True, max_length=64)),
                ('deposit_term', models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('% of Contract Value', '% of Contract Value')], default='Fixed Amount', max_length=64)),
                ('deposit_amount', models.CharField(blank=True, max_length=128)),
                ('term_percent', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_dispute_claim', models.CharField(blank=True, max_length=2048)),
                ('owner_dispute_claim', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('HANDLED', 'HANDLED'), ('IGNORED', 'IGNORED')], default='NEW', max_length=512)),
                ('referenceid', models.CharField(blank=True, max_length=128)),
                ('what', models.CharField(max_length=64)),
                ('who', models.CharField(max_length=512)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant_type', models.CharField(choices=[('TENANT', 'TENANT'), ('LANDLORD', 'LANDLORD'), ('AGENT', 'AGENT'), ('ADMIN', 'ADMIN'), ('TEST', 'TEST')], default='TEST', max_length=64)),
                ('registrant_first_name', models.DateTimeField(blank=True)),
                ('registrant_last_name', models.DateTimeField(blank=True)),
                ('registrant_phone', models.DateTimeField(blank=True)),
                ('registrant_email', models.DateTimeField(blank=True)),
            ],
        ),
    ]
