# Generated by Django 2.1.7 on 2019-02-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('accountType', models.CharField(choices=[('TENANT', 'TENANT'), ('OWNER', 'OWNER'), ('ADMIN', 'ADMIN'), ('TEST', 'TEST')], default='TEST', max_length=64)),
                ('accountStatus', models.CharField(choices=[('NEW', 'NEW'), ('VERIFIED', 'VERIFIED'), ('SUSPENDED', 'SUSPENDED')], default='NEW', max_length=64)),
                ('firstName', models.CharField(blank=True, max_length=256)),
                ('lastName', models.CharField(blank=True, max_length=256)),
                ('contactNumber', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='email address')),
                ('accountID', models.CharField(default='FFFF', max_length=256)),
                ('password', models.CharField(default='FFFF', max_length=256)),
                ('secret_key', models.CharField(blank=True, max_length=64)),
                ('password_reset_token', models.CharField(blank=True, max_length=512)),
                ('bankBSB', models.CharField(blank=True, max_length=64)),
                ('bankNo', models.CharField(blank=True, max_length=128)),
                ('bankName', models.CharField(blank=True, max_length=256)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('DISPUTE', 'DISPUTE'), ('COMPLETE', 'COMPLETE')], default='NEW', max_length=64)),
                ('isConfirmedByTenant', models.CharField(default='NO', max_length=64)),
                ('isConfirmedByOwner', models.CharField(default='NO', max_length=64)),
                ('ejariNo', models.CharField(max_length=128)),
                ('premisNo', models.CharField(max_length=128)),
                ('internalID', models.CharField(max_length=128)),
                ('tenantID', models.CharField(max_length=512)),
                ('ownerID', models.CharField(max_length=512)),
                ('tenant_first_name', models.CharField(blank=True, max_length=64)),
                ('tenant_last_name', models.CharField(blank=True, max_length=64)),
                ('tenant_phone', models.CharField(blank=True, max_length=32)),
                ('tenant_email', models.CharField(blank=True, max_length=256)),
                ('owner_first_name', models.CharField(blank=True, max_length=64)),
                ('owner_last_name', models.CharField(blank=True, max_length=64)),
                ('owner_phone', models.CharField(blank=True, max_length=32)),
                ('owner_email', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('statDate', models.DateTimeField(blank=True)),
                ('endDate', models.DateTimeField(blank=True)),
                ('depositAmount', models.CharField(blank=True, max_length=128)),
                ('depositHolding', models.CharField(blank=True, max_length=64)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('tenantDisputeClaim', models.CharField(blank=True, max_length=2048)),
                ('ownerDisputeClaim', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('HANDLED', 'HANDLED'), ('IGNORED', 'IGNORED')], default='NEW', max_length=512)),
                ('referenceid', models.CharField(blank=True, max_length=128)),
                ('what', models.CharField(max_length=64)),
                ('who', models.CharField(max_length=512)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant_type', models.CharField(choices=[('TENANT', 'TENANT'), ('LANDLORD', 'LANDLORD'), ('AGENT', 'AGENT'), ('ADMIN', 'ADMIN'), ('TEST', 'TEST')], default='TEST', max_length=64)),
                ('registrant_first_name', models.DateTimeField(blank=True)),
                ('registrant_last_name', models.DateTimeField(blank=True)),
                ('registrant_phone', models.DateTimeField(blank=True)),
                ('registrant_email', models.DateTimeField(blank=True)),
            ],
        ),
    ]
