# Generated by Django 2.1.7 on 2019-03-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='owner_first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='owner_last_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='tenant_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='tenant_first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='tenant_last_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='tenant_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='accountID',
            field=models.CharField(default='FFFF', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
