# Generated by Django 2.1.7 on 2019-03-18 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(blank=True, max_length=64)),
                ('property_type', models.CharField(blank=True, choices=[('', ''), ('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], max_length=64)),
                ('property_size_level', models.IntegerField(default=0, max_length=12)),
                ('property_size_from', models.IntegerField(default=0, max_length=12)),
                ('property_size_to', models.IntegerField(default=0, max_length=12)),
                ('tenant_name', models.CharField(blank=True, max_length=64)),
                ('owner_name', models.CharField(blank=True, max_length=64)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('address', models.CharField(max_length=512)),
                ('filter_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
