# Generated by Django 2.1.7 on 2019-03-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfilter',
            name='property_size_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appfilter',
            name='property_size_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appfilter',
            name='property_size_to',
            field=models.IntegerField(default=0),
        ),
    ]
