# Generated by Django 2.1.7 on 2019-03-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190318_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfilter',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appfilter',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
