# Generated by Django 2.1.7 on 2019-03-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190308_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountID',
            field=models.CharField(default='FFFF', max_length=256),
        ),
    ]
