# Generated by Django 2.1.7 on 2019-03-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190319_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfilter',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
