# Generated by Django 2.1.7 on 2019-03-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190310_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountID',
            field=models.CharField(default='FFFF', max_length=256, unique=True),
        ),
    ]
