# Generated by Django 2.1.7 on 2019-03-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190319_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfilter',
            name='property_size_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
